version: '2'

services:
  api:
    restart: always
    build: api/
    links:
      - db
    ports:
      - "8000:8000"
    volumes:
      - apifiles:/tmp

  db:
    restart: always
    image: mariadb:latest
    environment:
       MYSQL_ROOT_PASSWORD: strongp@ssw0RD
       MYSQL_DATABASE: yatodo
       MYSQL_USER: yatodouser
       MYSQL_PASSWORD: yatodo
    volumes:
      - maria:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    restart: always
    build: frontend/
    links:
      - api
    ports:
      - "80:80"


volumes:
  maria:
    driver: local

  apifiles:
    driver: local
