version: '2'

services:
  spring:
    restart: always
    build: ./src/main/docker
    links:
      - indb
    ports:
      - "8000:8000"
    volumes:
      - springfiles:/tmp

  indb:
    restart: always
    image: mysql:5.7
    environment:
       MYSQL_ROOT_PASSWORD: strongp@ssw0RD
       MYSQL_DATABASE: yatodo
       MYSQL_USER: yatodouser
       MYSQL_PASSWORD: strongp@ssw0RD
    volumes:
      - mysql:/var/lib/mysql

    ports:
      - "3306:3306"

volumes:
  mysql:
    driver: local

  springfiles:
    driver: local